name: Run tests for packer/terraform/ansible playbooks
on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Install cpu checkout
      run: sudo apt-get install -y cpu-checker

    - name: Check for kvm
      run: sudo kvm-ok

    - name: Install vagrant
      run: sudo apt-get install -y virtualbox vagrant

    - name: Install python packages
      run: pip install ansible molecule pytest-testinfra python-vagrant molecule-vagrant

    - name: Run tests
      run: make test
